
return {
	baseImage = "house_white",
	destinationType = "house",
	imageList = {
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_red",
		"house_white",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
	},
	canBeSick = true,
	canBeDrunk = true,
	exitRoadTypes = {
		straight = true,
	},
	spawnCar = {
		baseRate = 9,
		randomProp = 0.6,
		carType = "basic_car",
		targets = util.NormaliseWeightedList({
			{
				target = "highway",
				probability = 2,
			},
			{
				target = "house",
				probability = 1,
			},
		})
	},
}