
return {
	baseImage = "house_white",
	destinationType = "house",
	imageList = {
		"house_white",
		"house_green",
		"house_yellow",
		"house_green",
		"house_blue",
		"house_white",
		"house_red",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_white",
		"house_blue",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
		"house_white",
		"house_green",
		"house_yellow",
		"house_red",
		"house_blue",
	},
	canBeSick = true,
	canCatchFire = true,
	canBeDrunk = true,
	exitRoadTypes = {
		straight = true,
		ped_crossing = true,
	},
	spawnCar = {
		baseRate = 9,
		randomProp = 0.6,
		carType = "basic_car",
		targets = util.NormaliseWeightedList({
			{
				target = "highway",
				probability = 1.8,
			},
			{
				target = "house",
				probability = 1,
			},
			{
				target = "big_house",
				probability = 0.08,
			},
		})
	},
}