return {
	actual_image = "fire_popup",
	interface = false,
	alphaScale = true,
	scale = 0.1,
	lifeScale = 1,
	color = {1, 1, 1},
	walkMag = 1,
	walkRate = 5,
	inFront = 100,
	spawnOffset = {0, 0},
	duration = 1.8,
	drag = 4.2,
	gravity = -2,
}