return {
	image = "basic_car",
	maxSpeed = 1.15,
	accel = 2.2,
	deccel = 4.5,
	slowDeccel = 2,
	choiceRatio = {
		straight = 0.35,
		left = 0.25,
		right = 0.2,
	},
	length = 20,
	width = 12,
	rayStart = 2,
	rayLength = 32,
	rayTurnLength = 36,
	crossTrafficRay = 98,
	sideRayLength = 52,
	stopTimer = 0.4,
	friendlyCollision = true,
}